#!/usr/bin/env bash
# Build and run the app on the booted iOS Simulator (no Xcode UI).
#
# Pipeline: bake key into lib/generated/key.dart → flutter build ios (debug,
# simulator) → simctl install → simctl launch.
# (Reuses the same key-baking mechanism as android-3-start-app.sh for Android — see that
# script's comment for why: it's the one path proven to reliably survive into
# the compiled app on this toolchain, and lib/generated/key.dart is shared,
# platform-agnostic Dart code.)
#
# Requires a booted simulator (scripts/ios-2-start-simulator.sh). Config comes from
# the project's .env file (BITDRIFT_SDK_KEY, BITDRIFT_API_HOST, BACKEND_PORT) or
# the shell environment (which wins — export it to override).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FLUTTER_DIR="${FLUTTER_DIR:-$HOME/development/flutter}"
export PATH="$FLUTTER_DIR/bin:/opt/homebrew/bin:$PATH"
export LANG="${LANG:-en_US.UTF-8}"

BUNDLE_ID="io.bitdrift.bitdriftShopFlutter"

# 1. A booted simulator.
SIM_ID="$(xcrun simctl list devices booted | grep -oE '[0-9A-F]{8}-([0-9A-F]{4}-){3}[0-9A-F]{12}' | head -n1 || true)"
if [[ -z "$SIM_ID" ]]; then
  echo "No simulator booted. Start one first: bash scripts/ios-2-start-simulator.sh"
  exit 1
fi
echo "Targeting simulator: $SIM_ID"

# 2. Load config: .env fills in anything not already set in the shell env.
#    (shell exports win, so `export BITDRIFT_SDK_KEY=...` still overrides .env)
if [[ -f "$ROOT/.env" ]]; then
  while IFS= read -r line; do
    [[ "$line" =~ ^[[:space:]]*([A-Z][A-Z0-9_]*)=(.*)$ ]] || continue
    key="${BASH_REMATCH[1]}"
    [[ -n "${!key:-}" ]] && continue
    export "$key=${BASH_REMATCH[2]}"
  done < "$ROOT/.env"
fi

# 3. Bake the key into a plain Dart string literal (lib/generated/key.dart).
#    The committed stub is restored after install so the live key never
#    lingers on disk. Length only is ever printed.
GEN_KEY="$ROOT/lib/generated/key.dart"
stub_key_file() {
  if git -C "$ROOT" cat-file -e HEAD:lib/generated/key.dart 2>/dev/null; then
    git -C "$ROOT" checkout -- lib/generated/key.dart
  else
    printf '// GENERATED STUB — do not edit by hand or commit with a real key.\n// scripts/android-3-start-app.sh / scripts/ios-3-start-app.sh overwrite this with a live key before\n// each build and restore this stub immediately after installing.\nconst String generatedApiKey = %s;\n' "''" > "$GEN_KEY"
  fi
}
if [[ -n "${BITDRIFT_SDK_KEY:-}" ]]; then
  # If anything below fails, restore the stub — the live key must not linger.
  trap stub_key_file EXIT
  mkdir -p "$ROOT/lib/generated"
  printf '// GENERATED by ios-3-start-app.sh — contains a live key. Do not commit.\nconst String generatedApiKey = %s;\n' "'${BITDRIFT_SDK_KEY}'" > "$GEN_KEY"
  echo "Baked BITDRIFT_SDK_KEY (${#BITDRIFT_SDK_KEY} chars) into lib/generated/key.dart"
else
  echo "WARNING: BITDRIFT_SDK_KEY is empty — the app will start without a key"
fi

# 4. Compile-time defines (secondary injection path for the app's
#    String.fromEnvironment reads — see config.dart).
DART_DEFINES=()
[[ -n "${BITDRIFT_API_HOST:-}" ]] && DART_DEFINES+=(--dart-define="BITDRIFT_API_HOST=$BITDRIFT_API_HOST")
[[ -n "${BACKEND_PORT:-}" ]] && DART_DEFINES+=(--dart-define="BACKEND_PORT=$BACKEND_PORT")

# 5. Build for the simulator (debug — iOS release builds normally require a
#    codesigning identity even when the destination is a simulator).
cd "$ROOT"
flutter build ios --debug --simulator "${DART_DEFINES[@]}"

# 6. Install and launch.
APP="$ROOT/build/ios/iphonesimulator/Runner.app"
xcrun simctl install "$SIM_ID" "$APP"
xcrun simctl launch "$SIM_ID" "$BUNDLE_ID"
echo "Launched $BUNDLE_ID on $SIM_ID"
echo "Stop it with: xcrun simctl terminate $SIM_ID $BUNDLE_ID"

# 7. Restore the committed empty stub — the key is already baked into the app.
stub_key_file
echo "Restored lib/generated/key.dart stub"
