#!/usr/bin/env bash
# Build and run the app on the connected emulator (no Android Studio).
#
# Pipeline: bake key into lib/generated/key.dart → flutter build apk → adb install → launch.
# (--dart-define values have been observed to drop out of the release kernel in
# this toolchain, so the key rides in as a generated string literal instead.)
#
# Requires a running emulator (scripts/start-emulator.sh). Config comes from
# the project's .env file (BITDRIFT_SDK_KEY, BITDRIFT_API_HOST, BACKEND_PORT) or
# the shell environment (which wins — export it to override).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FLUTTER_DIR="${FLUTTER_DIR:-$HOME/development/flutter}"
SDK_DIR="${ANDROID_HOME:-$HOME/Library/Android/sdk}"
export PATH="$FLUTTER_DIR/bin:$SDK_DIR/platform-tools:$PATH"

# 1. A connected emulator.
EMU_ID="$(adb devices | awk 'NR>1 && $2=="device"{print $1}' | grep -E '^emulator-' | head -n1 || true)"
if [[ -z "$EMU_ID" ]]; then
  echo "No emulator attached. Start one first: bash scripts/start-emulator.sh"
  exit 1
fi
echo "Targeting emulator: $EMU_ID"

# 2. Load config: .env fills in anything not already set in the shell env.
#    (shell exports win, so `export BITDRIFT_SDK_KEY=...` still overrides .env)
if [[ -f "$ROOT/.env" ]]; then
  while IFS= read -r line; do
    [[ "$line" =~ ^[[:space:]]*([A-Z][A-Z0-9_]*)=(.*)$ ]] || continue
    key="${BASH_REMATCH[1]}"
    [[ -n "${!key:-}" ]] && continue
    export "$key=${BASH_REMATCH[2]}"
  done < "$ROOT/.env"
fi

# 3. Bake the key into a plain Dart string literal (lib/generated/key.dart).
#    --dart-define values have been observed to drop out of the release
#    kernel in this toolchain; a literal is baked in reliably (verified in
#    libapp.so). The committed stub is restored after install so the live
#    key never lingers on disk. Length only is ever printed.
GEN_KEY="$ROOT/lib/generated/key.dart"
stub_key_file() {
  if git -C "$ROOT" cat-file -e HEAD:lib/generated/key.dart 2>/dev/null; then
    git -C "$ROOT" checkout -- lib/generated/key.dart
  else
    printf '// GENERATED STUB — do not edit by hand or commit with a real key.\n// scripts/run-app.sh overwrites this with a live key before each build and\n// restores this stub immediately after installing the APK.\nconst String generatedApiKey = %s;\n' "''" > "$GEN_KEY"
  fi
}
if [[ -n "${BITDRIFT_SDK_KEY:-}" ]]; then
  # If anything below fails, restore the stub — the live key must not linger.
  trap stub_key_file EXIT
  mkdir -p "$ROOT/lib/generated"
  printf '// GENERATED by scripts/run-app.sh — contains a live key. Do not commit.\nconst String generatedApiKey = %s;\n' "'${BITDRIFT_SDK_KEY}'" > "$GEN_KEY"
  echo "Baked BITDRIFT_SDK_KEY (${#BITDRIFT_SDK_KEY} chars) into lib/generated/key.dart"
else
  echo "WARNING: BITDRIFT_SDK_KEY is empty — the app will start without a key"
fi
# 4. Compile-time defines (kept as a secondary injection path for the app's
#    String.fromEnvironment reads).
DART_DEFINES=()
[[ -n "${BITDRIFT_API_HOST:-}" ]] && DART_DEFINES+=(--dart-define="BITDRIFT_API_HOST=$BITDRIFT_API_HOST")
[[ -n "${BACKEND_PORT:-}" ]] && DART_DEFINES+=(--dart-define="BACKEND_PORT=$BACKEND_PORT")

# 5. Build the release APK with the compile-time defines.
cd "$ROOT"
flutter build apk --release "${DART_DEFINES[@]}"

# 6. Install and launch.
APK="$ROOT/build/app/outputs/flutter-apk/app-release.apk"
adb -s "$EMU_ID" install -r "$APK"
adb -s "$EMU_ID" shell am start -n ai.bitdrift.shop.flutter/.MainActivity
echo "Launched ai.bitdrift.shop.flutter on $EMU_ID"
echo "Stop it with: adb -s $EMU_ID shell am force-stop ai.bitdrift.shop.flutter"

# 7. Restore the committed empty stub — the key is already baked into the APK.
stub_key_file
echo "Restored lib/generated/key.dart stub"
